// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Locate struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type LocateInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type Performance struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Discription string   `json:"discription"`
	Start       string   `json:"start"`
	Tags        []string `json:"tags"`
	Finish      string   `json:"finish"`
	Thumbnail   *string  `json:"thumbnail"`
	Location    *Locate  `json:"location"`
	Address     string   `json:"address"`
	Artist      *User    `json:"artist"`
}

type PerformanceInput struct {
	Name        string       `json:"name"`
	Discription string       `json:"discription"`
	Start       string       `json:"start"`
	Finish      string       `json:"finish"`
	Thumbnail   *string      `json:"thumbnail"`
	Location    *LocateInput `json:"location"`
	Address     string       `json:"address"`
	Tags        []string     `json:"tags"`
}

type UpdateUserIDInput struct {
	ID    string `json:"id"`
	NewID string `json:"newID"`
}

type UpdateUserInput struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	ImageIcon *string `json:"imageIcon"`
}

type User struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	ImageIcon     string   `json:"imageIcon"`
	Thumbnail     string   `json:"thumbnail"`
	FollowArtists []string `json:"followArtists"`
	Performances  []string `json:"performances"`
}
